apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: hello
  labels:
    name: hello
spec:
  triggers:
  - type: ConfigChange
  source:
    type: Git
    git:
      uri: "https://github.com/tektutor/openshift-tekton-june2024.git"
      ref: main
    contextDir: "Day6/BuildConfig"
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'tektutor-spring-hello:latest'
