apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: tektutorjegan.jfrog.io/jegan-docker-docker/hello-spring-microservice:2.0
        name: hello-spring-microservice
      imagePullSecrets:
      - name: private-jfrog-image-registry-new
