apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-{{.Values.pv_label}}
  labels:
    name: {{.Values.pv_label}} 
spec:
  capacity:
    storage: {{.Values.mariadb_pv_size}} 
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{.Values.nfs_server_ip}} 
    path: {{.Values.nfs_mariadb_path}} 
