apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: tektutor.jfrog.io/tektutor-docker/hello-microservice:1.0
        name: hello-microservice
      imagePullSecrets:
      - name: private-jfrog-image-registry 
