apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-jegan #Replace 'jegan' with your name
  labels:
    name: jegan #Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108 #Replace this IP address with 192.168.1.22/23/24 based on which linux server you are connected 
    path: /var/nfs/jegan/mariadb #Replace this path with your path /var/nfs/user15/mariadb
