apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.108  # Replace this IP with 192.168.1.22 or 192.168.1.23 or 192.168.1.24 as per your linux server ip
    path: /var/nfs/jegan/tekton # Replace this folder as your nfs share path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  selector:
    matchLabels:
      name: jegan # Replace 'jegan' with your name
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: github-clone-tr-
spec:
  taskRef:
    name: git-clone
  params:
  - name: url
    value: https://github.com/tektutor/openshift-tekton-june2024.git

  - name: revision
    value: main

  - name: subdirectory
    value: source
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan  #Replace 'jegan' with your name
