apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: maven-build-tr-
spec:
  taskRef:
    name: maven
  params:
  - name: CONTEXT_DIR
    value: source/Day6/BuildConfig

  - name: deleteExisting
    value: false

  - name: GOALS
    value:
    - -Dmaven.repo.local=$(workspaces.maven-settings.path)
    - clean
    - package

  workspaces:
  - name: source
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan #Replace 'jegan' with your name

  - name: maven-settings
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan #Replace 'jegan' with your name
    subPath: settings

  - name: maven-local-repo
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan #Replace 'jegan' with your name
    subPath: m2 


