apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: steps-sharing-data
spec:
  results:
  - name: data
    description: Data to be shared
  steps:
  - name: step1
    image: registry.access.redhat.com/ubi8/ubi-minimal
    command:
    - /bin/bash
    args:
    - "-c"
    - echo -n "Plain data converted to Base 64"|base64 > $(results.data.path)
  - name: step2
    image: registry.access.redhat.com/ubi8/ubi-minimal
    command:
    - /bin/bash
    args:
    - "-c"
    - cat $(results.data.path)
      

